accounts:
  - name: alice
    coins: ["200000000nusic"]
  - name: bob
    coins: ["100000000nusic"]
validator:
  name: alice
  staked: "100000000nusic"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000nusic"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "nusic"