version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 200000000nusic
- name: bob
  coins:
  - 10000000000nusic
- name: logesh
  coins:
  - 100000000nusic
faucet:
  name: bob
  coins:
  - 100000nusic
  host: 0.0.0.0:4500
client:
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    staking:
      params:
        bond_denom: nusic
validators:
- name: alice
  bonded: 100000000nusic
